INSERT into category (description) values ('American');
INSERT into category (description) values ('Italian');
INSERT into category (description) values ('Mexican');
INSERT into category (description) values ('Fast food');
INSERT into unit_of_measure (description) values ('Teaspoon');
INSERT into unit_of_measure (description) values ('Tablespoon');
INSERT into unit_of_measure (description) values ('Cup');
INSERT into unit_of_measure (description) values ('Pinch');
INSERT into unit_of_measure (description) values ('Ounce');
INSERT into unit_of_measure (description) values ('Each');
INSERT into unit_of_measure (description) values ('Dash');
INSERT into unit_of_measure (description) values ('Pint');